

//
//  DBColorNames.m
//  DBColorNames
//
//  Created by Daniel Beard on 10/16/14.
//  Copyright (c) 2014 DanielBeard. All rights reserved.
//

/*
 The MIT License (MIT)
 
 Copyright (c) 2014 Daniel Beard
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#import "DBColorNames.h"
#import <UIKit/UIKit.h>

static const NSString *kId = @"colorId";

@interface DBColorNames ()

@property (nonatomic, strong) NSDictionary *colorMap;

@end

@implementation DBColorNames

- (instancetype)init {
    self = [super init];
    if (self) {
        [self setupColorMap];
    }
    return self;
}

- (UIColor *)colorFromRGBFloat:(int)rgbValue {
    return [UIColor
            colorWithRed : ((float)((rgbValue & 0xFF0000) >> 16)) / 255.0
            green : ((float)((rgbValue & 0xFF00) >> 8)) / 255.0
            blue : ((float)(rgbValue & 0xFF)) / 255.0
            alpha : 1.0];
}

- (void)setupColorMap {
    self.colorMap = @{
                      @"blue": @{kId:	@(0xacc2d9)},
                      @"green": @{kId:	@(0x56ae57)},
                      @"grey": @{kId:	@(0xb2996e)},
                      @"green": @{kId:	@(0xa8ff04)},
                      @"green": @{kId:	@(0x69d84f)},
                      @"purple": @{kId:	@(0x894585)},
                      @"green": @{kId:	@(0x70b23f)},
                      @"blue": @{kId:	@(0xd4ffff)},
                      @"brown": @{kId:	@(0x65ab7c)},
                      @"purple": @{kId:	@(0x952e8f)},
                      @"tan": @{kId:	@(0xfcfc81)},
                      @"grey": @{kId:	@(0xa5a391)},
                      @"green": @{kId:	@(0x388004)},
                      @"teal": @{kId:	@(0x4c9085)},
                      @"grey": @{kId:	@(0x5e9b8a)},
                      @"yellow": @{kId:	@(0xefb435)},
                      @"pink": @{kId:	@(0xd99b82)},
                      @"green": @{kId:	@(0x0a5f38)},
                      @"blue": @{kId:	@(0x0c06f7)},
                      @"green": @{kId:	@(0x61de2a)},
                      @"blue": @{kId:	@(0x3778bf)},
                      @"blue": @{kId:	@(0x2242c7)},
                      @"blue": @{kId:	@(0x533cc6)},
                      @"green": @{kId:	@(0x9bb53c)},
                      @"green": @{kId:	@(0x05ffa6)},
                      @"green": @{kId:	@(0x1f6357)},
                      @"turquoise": @{kId:	@(0x017374)},
                      @"teal": @{kId:	@(0x0cb577)},
                      @"pink": @{kId:	@(0xff0789)},
                      @"grey": @{kId:	@(0xafa88b)},
                      @"aqua": @{kId:	@(0x08787f)},
                      @"pink": @{kId:	@(0xdd85d7)},
                      @"green": @{kId:	@(0xa6c875)},
                      @"green": @{kId:	@(0xa7ffb5)},
                      @"olive": @{kId:	@(0xc2b709)},
                      @"pink": @{kId:	@(0xe78ea5)},
                      @"purple": @{kId:	@(0x966ebd)},
                      @"khaki": @{kId:	@(0xccad60)},
                      @"grey": @{kId:	@(0xac86a8)},
                      @"purple": @{kId:	@(0x947e94)},
                      @"purple": @{kId:	@(0x983fb2)},
                      @"pink": @{kId:	@(0xff63e9)},
                      @"green": @{kId:	@(0xb2fba5)},
                      @"olive": @{kId:	@(0x63b365)},
                      @"green": @{kId:	@(0x8ee53f)},
                      @"grey": @{kId:	@(0xb7e1a1)},
                      @"orange": @{kId:	@(0xff6f52)},
                      @"green": @{kId:	@(0xbdf8a3)},
                      @"brown": @{kId:	@(0xd3b683)},
                      @"off white": @{kId:	@(0xfffcc4)},
                      @"purple": @{kId:	@(0x430541)},
                      @"pink": @{kId:	@(0xffb2d0)},
                      @"red": @{kId:	@(0x997570)},
                      @"brown": @{kId:	@(0xad900d)},
                      @"purple": @{kId:	@(0xc48efd)},
                      @"blue": @{kId:	@(0x507b9c)},
                      @"brown": @{kId:	@(0x7d7103)},
                      @"yellow": @{kId:	@(0xfffd78)},
                      @"pink": @{kId:	@(0xda467d)},
                      @"brown": @{kId:	@(0x410200)},
                      @"beige": @{kId:	@(0xc9d179)},
                      @"tan": @{kId:	@(0xfffa86)},
                      @"blue": @{kId:	@(0x5684ae)},
                      @"grey": @{kId:	@(0x6b7c85)},
                      @"green": @{kId:	@(0x6f6c0a)},
                      @"purple": @{kId:	@(0x7e4071)},
                      @"green": @{kId:	@(0x009337)},
                      @"yellow": @{kId:	@(0xd0e429)},
                      @"yellow": @{kId:	@(0xfff917)},
                      @"blue": @{kId:	@(0x1d5dec)},
                      @"green": @{kId:	@(0x054907)},
                      @"yellow": @{kId:	@(0xb5ce08)},
                      @"green": @{kId:	@(0x8fb67b)},
                      @"green": @{kId:	@(0xc8ffb0)},
                      @"gold": @{kId:	@(0xfdde6c)},
                      @"yellow": @{kId:	@(0xffdf22)},
                      @"tan": @{kId:	@(0xa9be70)},
                      @"purple": @{kId:	@(0x6832e3)},
                      @"tan": @{kId:	@(0xfdb147)},
                      @"toupe": @{kId:	@(0xc7ac7d)},
                      @"cream": @{kId:	@(0xfff39a)},
                      @"red": @{kId:	@(0x850e04)},
                      @"lavendar": @{kId:	@(0xefc0fe)},
                      @"green": @{kId:	@(0x40fd14)},
                      @"green": @{kId:	@(0xb6c406)},
                      @"yellow": @{kId:	@(0x9dff00)},
                      @"grey": @{kId:	@(0x3c4142)},
                      @"orange": @{kId:	@(0xf2ab15)},
                      @"brown": @{kId:	@(0xac4f06)},
                      @"green": @{kId:	@(0xc4fe82)},
                      @"green": @{kId:	@(0x2cfa1f)},
                      @"sienna": @{kId:	@(0x9a6200)},
                      @"purple": @{kId:	@(0xca9bf7)},
                      @"brown": @{kId:	@(0x875f42)},
                      @"blue": @{kId:	@(0x3a2efe)},
                      @"orange": @{kId:	@(0xfd8d49)},
                      @"brown": @{kId:	@(0x8b3103)},
                      @"brown": @{kId:	@(0xcba560)},
                      @"green": @{kId:	@(0x698339)},
                      @"teal": @{kId:	@(0x0cdc73)},
                      @"burnt sienna": @{kId:	@(0xb75203)},
                      @"camo": @{kId:	@(0x7f8f4e)},
                      @"blue": @{kId:	@(0x26538d)},
                      @"green": @{kId:	@(0x63a950)},
                      @"red": @{kId:	@(0xc87f89)},
                      @"green": @{kId:	@(0xb1fc99)},
                      @"pink": @{kId:	@(0xff9a8a)},
                      @"pink": @{kId:	@(0xf6688e)},
                      @"turquoise": @{kId:	@(0x76fda8)},
                      @"green": @{kId:	@(0x53fe5c)},
                      @"green": @{kId:	@(0x4efd54)},
                      @"seafoam": @{kId:	@(0xa0febf)},
                      @"blue": @{kId:	@(0x7bf2da)},
                      @"green": @{kId:	@(0xbcf5a6)},
                      @"orange": @{kId:	@(0xca6b02)},
                      @"blue": @{kId:	@(0x107ab0)},
                      @"blue": @{kId:	@(0x2138ab)},
                      @"teal": @{kId:	@(0x719f91)},
                      @"orange": @{kId:	@(0xfdb915)},
                      @"tan": @{kId:	@(0xfefcaf)},
                      @"khaki": @{kId:	@(0xfcf679)},
                      @"brown": @{kId:	@(0x1d0200)},
                      @"orange": @{kId:	@(0xcb6843)},
                      @"blue": @{kId:	@(0x31668a)},
                      @"blue": @{kId:	@(0x247afd)},
                      @"cream": @{kId:	@(0xffffb6)},
                      @"green": @{kId:	@(0x90fda9)},
                      @"grey": @{kId:	@(0x86a17d)},
                      @"gold": @{kId:	@(0xfddc5c)},
                      @"blue": @{kId:	@(0x78d1b6)},
                      @"yellow": @{kId:	@(0x13bbaf)},
                      @"pink": @{kId:	@(0xfb5ffc)},
                      @"green": @{kId:	@(0x20f986)},
                      @"tan": @{kId:	@(0xffe36e)},
                      @"fuchsia": @{kId:	@(0x9d0759)},
                      @"indigo": @{kId:	@(0x3a18b1)},
                      @"green": @{kId:	@(0xc2ff89)},
                      @"magenta": @{kId:	@(0xd767ad)},
                      @"purple": @{kId:	@(0x720058)},
                      @"yellow": @{kId:	@(0xffda03)},
                      @"blue": @{kId:	@(0x01c08d)},
                      @"leather": @{kId:	@(0xac7434)},
                      @"green": @{kId:	@(0x014600)},
                      @"purple": @{kId:	@(0x9900fa)},
                      @"blue": @{kId:	@(0x02066f)},
                      @"brown": @{kId:	@(0x8e7618)},
                      @"pink": @{kId:	@(0xd1768f)},
                      @"green": @{kId:	@(0x96b403)},
                      @"yellow": @{kId:	@(0xfdff63)},
                      @"grey": @{kId:	@(0x95a3a6)},
                      @"taupe": @{kId:	@(0x7f684e)},
                      @"purple": @{kId:	@(0x751973)},
                      @"green": @{kId:	@(0x089404)},
                      @"pink": @{kId:	@(0xff6163)},
                      @"sage": @{kId:	@(0x598556)},
                      @"blue": @{kId:	@(0x214761)},
                      @"blue": @{kId:	@(0x3c73a8)},
                      @"grey": @{kId:	@(0xba9e88)},
                      @"blue": @{kId:	@(0x021bf9)},
                      @"purple": @{kId:	@(0x734a65)},
                      @"blue": @{kId:	@(0x23c48b)},
                      @"green": @{kId:	@(0x8fae22)},
                      @"khaki": @{kId:	@(0xe6f2a2)},
                      @"blue": @{kId:	@(0x4b57db)},
                      @"hot pink": @{kId:	@(0xd90166)},
                      @"navy": @{kId:	@(0x015482)},
                      @"red": @{kId:	@(0x9d0216)},
                      @"green": @{kId:	@(0x728f02)},
                      @"peach": @{kId:	@(0xffe5ad)},
                      @"purple": @{kId:	@(0x4e0550)},
                      @"gold": @{kId:	@(0xf9bc08)},
                      @"red": @{kId:	@(0xff073a)},
                      @"pink": @{kId:	@(0xc77986)},
                      @"blue": @{kId:	@(0xd6fffe)},
                      @"orange": @{kId:	@(0xfe4b03)},
                      @"purple": @{kId:	@(0xfd5956)},
                      @"yellow": @{kId:	@(0xfce166)},
                      @"brown": @{kId:	@(0xb2713d)},
                      @"grey": @{kId:	@(0x1f3b4d)},
                      @"green": @{kId:	@(0x699d4c)},
                      @"turquoise": @{kId:	@(0x56fca2)},
                      @"pink": @{kId:	@(0xfb5581)},
                      @"blue": @{kId:	@(0x3e82fc)},
                      @"green": @{kId:	@(0xa0bf16)},
                      @"white": @{kId:	@(0xd6fffa)},
                      @"blue": @{kId:	@(0x4f738e)},
                      @"salmon": @{kId:	@(0xffb19a)},
                      @"green": @{kId:	@(0x5c8b15)},
                      @"green": @{kId:	@(0x54ac68)},
                      @"grey": @{kId:	@(0x89a0b0)},
                      @"green": @{kId:	@(0x7ea07a)},
                      @"neon green": @{kId:	@(0x1bfc06)},
                      @"blue": @{kId:	@(0xcafffb)},
                      @"mint": @{kId:	@(0xb6ffbb)},
                      @"umber": @{kId:	@(0xa75e09)},
                      @"blue": @{kId:	@(0x152eff)},
                      @"lavender": @{kId:	@(0x8d5eb7)},
                      @"teal": @{kId:	@(0x5f9e8f)},
                      @"blue": @{kId:	@(0x63f7b4)},
                      @"green": @{kId:	@(0x606602)},
                      @"pink": @{kId:	@(0xfc86aa)},
                      @"burgundy": @{kId:	@(0x8c0034)},
                      @"green": @{kId:	@(0x758000)},
                      @"tan": @{kId:	@(0xab7e4c)},
                      @"navy": @{kId:	@(0x030764)},
                      @"red": @{kId:	@(0xfe86a4)},
                      @"red": @{kId:	@(0xd5174e)},
                      @"mauve": @{kId:	@(0xfed0fc)},
                      @"maroon": @{kId:	@(0x680018)},
                      @"yellow": @{kId:	@(0xfedf08)},
                      @"orange": @{kId:	@(0xfe420f)},
                      @"green": @{kId:	@(0x6f7c00)},
                      @"red": @{kId:	@(0xca0147)},
                      @"grey": @{kId:	@(0x1b2431)},
                      @"turquoise": @{kId:	@(0x00fbb0)},
                      @"red": @{kId:	@(0xdb5856)},
                      @"yellow": @{kId:	@(0xddd618)},
                      @"cyan": @{kId:	@(0x41fdfe)},
                      @"coral": @{kId:	@(0xcf524e)},
                      @"green": @{kId:	@(0x21c36f)},
                      @"burgundy": @{kId:	@(0xa90308)},
                      @"red": @{kId:	@(0x6e1005)},
                      @"pink": @{kId:	@(0xfe828c)},
                      @"camouflage": @{kId:	@(0x4b6113)},
                      @"green": @{kId:	@(0x4da409)},
                      @"pink": @{kId:	@(0xbeae8a)},
                      @"blue": @{kId:	@(0x0339f8)},
                      @"yellow": @{kId:	@(0xa88f59)},
                      @"purple": @{kId:	@(0x5d21d0)},
                      @"red": @{kId:	@(0xfeb209)},
                      @"blue": @{kId:	@(0x4e518b)},
                      @"brown": @{kId:	@(0x964e02)},
                      @"grey": @{kId:	@(0x85a3b2)},
                      @"pink": @{kId:	@(0xff69af)},
                      @"blue": @{kId:	@(0xc3fbf4)},
                      @"green": @{kId:	@(0x2afeb7)},
                      @"brown": @{kId:	@(0x005f6a)},
                      @"blue": @{kId:	@(0x0c1793)},
                      @"yellow": @{kId:	@(0xffff81)},
                      @"orange": @{kId:	@(0xf0833a)},
                      @"yellow": @{kId:	@(0xf1f33f)},
                      @"olive": @{kId:	@(0xb1d27b)},
                      @"orange": @{kId:	@(0xfc824a)},
                      @"green": @{kId:	@(0x71aa34)},
                      @"grey": @{kId:	@(0xb7c9e2)},
                      @"brown": @{kId:	@(0x4b0101)},
                      @"purple": @{kId:	@(0xa552e6)},
                      @"orange": @{kId:	@(0xaf2f0d)},
                      @"blue": @{kId:	@(0x8b88f8)},
                      @"green": @{kId:	@(0x9af764)},
                      @"mint": @{kId:	@(0xa6fbb2)},
                      @"yellow": @{kId:	@(0xffc512)},
                      @"red": @{kId:	@(0x750851)},
                      @"orange": @{kId:	@(0xc14a09)},
                      @"red": @{kId:	@(0xfe2f4a)},
                      @"blue": @{kId:	@(0x0203e2)},
                      @"blue": @{kId:	@(0x0a437a)},
                      @"purple": @{kId:	@(0xa50055)},
                      @"yellow": @{kId:	@(0xae8b0c)},
                      @"pink": @{kId:	@(0xfd798f)},
                      @"yellow": @{kId:	@(0xbfac05)},
                      @"green": @{kId:	@(0x3eaf76)},
                      @"red": @{kId:	@(0xc74767)},
                      @"red": @{kId:	@(0xb9484e)},
                      @"grey": @{kId:	@(0x647d8e)},
                      @"yellow": @{kId:	@(0xbffe28)},
                      @"purple": @{kId:	@(0xd725de)},
                      @"yellow": @{kId:	@(0xb29705)},
                      @"purple": @{kId:	@(0x673a3f)},
                      @"purple": @{kId:	@(0xa87dc2)},
                      @"yellow": @{kId:	@(0xfafe4b)},
                      @"red": @{kId:	@(0xc0022f)},
                      @"aqua": @{kId:	@(0x0e87cc)},
                      @"grey": @{kId:	@(0x8d8468)},
                      @"purple": @{kId:	@(0xad03de)},
                      @"green": @{kId:	@(0x8cff9e)},
                      @"green": @{kId:	@(0x94ac02)},
                      @"blue": @{kId:	@(0xc4fff7)},
                      @"yellow": @{kId:	@(0xfdee73)},
                      @"green": @{kId:	@(0x33b864)},
                      @"pale": @{kId:	@(0xfff9d0)},
                      @"grey": @{kId:	@(0x758da3)},
                      @"magenta": @{kId:	@(0xf504c9)},
                      @"grey": @{kId:	@(0x77a1b5)},
                      @"purple": @{kId:	@(0x8756e4)},
                      @"green": @{kId:	@(0x889717)},
                      @"brown": @{kId:	@(0xc27e79)},
                      @"aquamarine": @{kId:	@(0x017371)},
                      @"brown": @{kId:	@(0x9f8303)},
                      @"yellow": @{kId:	@(0xf7d560)},
                      @"blue": @{kId:	@(0xbdf6fe)},
                      @"green": @{kId:	@(0x75b84f)},
                      @"olive": @{kId:	@(0x9cbb04)},
                      @"grey": @{kId:	@(0x29465b)},
                      @"camouflage": @{kId:	@(0x696006)},
                      @"green": @{kId:	@(0xadf802)},
                      @"periwinkle": @{kId:	@(0xc1c6fc)},
                      @"green": @{kId:	@(0x35ad6b)},
                      @"yellow": @{kId:	@(0xfffd37)},
                      @"purple": @{kId:	@(0xa442a0)},
                      @"pink": @{kId:	@(0xf36196)},
                      @"brown": @{kId:	@(0x947706)},
                      @"pink": @{kId:	@(0xfff4f2)},
                      @"green": @{kId:	@(0x1e9167)},
                      @"green brown": @{kId:	@(0xb5c306)},
                      @"yellow": @{kId:	@(0xfeff7f)},
                      @"green": @{kId:	@(0xcffdbc)},
                      @"green": @{kId:	@(0x0add08)},
                      @"lime": @{kId:	@(0x87fd05)},
                      @"mint": @{kId:	@(0x1ef876)},
                      @"aquamarine": @{kId:	@(0x7bfdc7)},
                      @"sage": @{kId:	@(0xbcecac)},
                      @"yellow green": @{kId:	@(0xbbf90f)},
                      @"brown": @{kId:	@(0xab9004)},
                      @"seafoam": @{kId:	@(0x1fb57a)},
                      @"teal": @{kId:	@(0x00555a)},
                      @"gray": @{kId:	@(0xa484ac)},
                      @"orange": @{kId:	@(0xc45508)},
                      @"blue": @{kId:	@(0x3f829d)},
                      @"forest green": @{kId:	@(0x548d44)},
                      @"lilac": @{kId:	@(0xc95efb)},
                      @"green": @{kId:	@(0x3ae57f)},
                      @"blue": @{kId:	@(0x016795)},
                      @"green": @{kId:	@(0x87a922)},
                      @"orange": @{kId:	@(0xf0944d)},
                      @"purple": @{kId:	@(0x5d1451)},
                      @"green": @{kId:	@(0x25ff29)},
                      @"yellow": @{kId:	@(0xd0fe1d)},
                      @"orange": @{kId:	@(0xffa62b)},
                      @"green": @{kId:	@(0x01b44c)},
                      @"pink": @{kId:	@(0xff6cb5)},
                      @"purple": @{kId:	@(0x6b4247)},
                      @"yellow": @{kId:	@(0xc7c10c)},
                      @"cyan": @{kId:	@(0xb7fffa)},
                      @"lime": @{kId:	@(0xaeff6e)},
                      @"red": @{kId:	@(0xec2d01)},
                      @"green": @{kId:	@(0x76ff7b)},
                      @"red purple": @{kId:	@(0x730039)},
                      @"blue": @{kId:	@(0x040348)},
                      @"pink": @{kId:	@(0xdf4ec8)},
                      @"red": @{kId:	@(0x6ecb3c)},
                      @"green": @{kId:	@(0x8f9805)},
                      @"green": @{kId:	@(0x5edc1f)},
                      @"purple": @{kId:	@(0xd94ff5)},
                      @"green": @{kId:	@(0xc8fd3d)},
                      @"black": @{kId:	@(0x070d0d)},
                      @"blue": @{kId:	@(0x4984b8)},
                      @"green": @{kId:	@(0x51b73b)},
                      @"yellow": @{kId:	@(0xac7e04)},
                      @"blue": @{kId:	@(0x4e5481)},
                      @"brown": @{kId:	@(0x876e4b)},
                      @"green": @{kId:	@(0x58bc08)},
                      @"green": @{kId:	@(0x2fef10)},
                      @"green": @{kId:	@(0x2dfe54)},
                      @"green": @{kId:	@(0x0aff02)},
                      @"green": @{kId:	@(0x9cef43)},
                      @"navy": @{kId:	@(0x18d17b)},
                      @"olive": @{kId:	@(0x35530a)},
                      @"blue": @{kId:	@(0x1805db)},
                      @"purple": @{kId:	@(0x6258c4)},
                      @"orange": @{kId:	@(0xff964f)},
                      @"orange": @{kId:	@(0xffab0f)},
                      @"purple": @{kId:	@(0x8f8ce7)},
                      @"teal": @{kId:	@(0x24bca8)},
                      @"purple": @{kId:	@(0x3f012c)},
                      @"green": @{kId:	@(0xcbf85f)},
                      @"orange": @{kId:	@(0xff724c)},
                      @"purple": @{kId:	@(0x280137)},
                      @"purple": @{kId:	@(0xb36ff6)},
                      @"mint": @{kId:	@(0x48c072)},
                      @"tan": @{kId:	@(0xbccb7a)},
                      @"burgundy": @{kId:	@(0xa8415b)},
                      @"turquoise": @{kId:	@(0x06b1c4)},
                      @"pink": @{kId:	@(0xcd7584)},
                      @"khaki": @{kId:	@(0xf1da7a)},
                      @"pink": @{kId:	@(0xff0490)},
                      @"purple": @{kId:	@(0x805b87)},
                      @"green": @{kId:	@(0x50a747)},
                      @"grey": @{kId:	@(0xa8a495)},
                      @"yellow": @{kId:	@(0xcfff04)},
                      @"yellow": @{kId:	@(0xffff7e)},
                      @"pink": @{kId:	@(0xff7fa7)},
                      @"red": @{kId:	@(0xef4026)},
                      @"navy": @{kId:	@(0x3c9992)},
                      @"brown": @{kId:	@(0x886806)},
                      @"turquoise": @{kId:	@(0x04f489)},
                      @"yellow": @{kId:	@(0xfef69e)},
                      @"tan": @{kId:	@(0xcfaf7b)},
                      @"grey": @{kId:	@(0x3b719f)},
                      @"red": @{kId:	@(0xfdc1c5)},
                      @"mint": @{kId:	@(0x20c073)},
                      @"purple": @{kId:	@(0x9b5fc0)},
                      @"green": @{kId:	@(0x0f9b8e)},
                      @"brown": @{kId:	@(0x742802)},
                      @"green": @{kId:	@(0x9db92c)},
                      @"green": @{kId:	@(0xa4bf20)},
                      @"orange": @{kId:	@(0xcd5909)},
                      @"grey": @{kId:	@(0xada587)},
                      @"red": @{kId:	@(0xbe013c)},
                      @"aqua": @{kId:	@(0xb8ffeb)},
                      @"orange": @{kId:	@(0xdc4d01)},
                      @"brown": @{kId:	@(0xa2653e)},
                      @"green": @{kId:	@(0x638b27)},
                      @"green": @{kId:	@(0x419c03)},
                      @"green": @{kId:	@(0xb1ff65)},
                      @"grey": @{kId:	@(0x9dbcd4)},
                      @"grey": @{kId:	@(0xfdfdfe)},
                      @"green": @{kId:	@(0x77ab56)},
                      @"blue": @{kId:	@(0x464196)},
                      @"purple": @{kId:	@(0x990147)},
                      @"green": @{kId:	@(0xbefd73)},
                      @"teal": @{kId:	@(0x32bf84)},
                      @"brown": @{kId:	@(0xaf6f09)},
                      @"magenta": @{kId:	@(0xa0025c)},
                      @"peach": @{kId:	@(0xffd8b1)},
                      @"brown": @{kId:	@(0x7f4e1e)},
                      @"brown": @{kId:	@(0xbf9b0c)},
                      @"green": @{kId:	@(0x6ba353)},
                      @"purple": @{kId:	@(0xf075e6)},
                      @"blue": @{kId:	@(0x7bc8f6)},
                      @"blue": @{kId:	@(0x475f94)},
                      @"gold": @{kId:	@(0xf5bf03)},
                      @"beige": @{kId:	@(0xfffeb6)},
                      @"yellow": @{kId:	@(0xfffd74)},
                      @"purple": @{kId:	@(0x895b7b)},
                      @"blue": @{kId:	@(0x436bad)},
                      @"yellow": @{kId:	@(0xd0c101)},
                      @"yellow": @{kId:	@(0xc6f808)},
                      @"orange": @{kId:	@(0xf43605)},
                      @"green": @{kId:	@(0x02c14d)},
                      @"orange": @{kId:	@(0xb25f03)},
                      @"green": @{kId:	@(0x2a7e19)},
                      @"violet": @{kId:	@(0x490648)},
                      @"black": @{kId:	@(0x536267)},
                      @"blue": @{kId:	@(0x5a06ef)},
                      @"red": @{kId:	@(0xcf0234)},
                      @"tan": @{kId:	@(0xc4a661)},
                      @"grey": @{kId:	@(0x978a84)},
                      @"indigo": @{kId:	@(0x1f0954)},
                      @"indigo": @{kId:	@(0x03012d)},
                      @"green": @{kId:	@(0x2bb179)},
                      @"grey": @{kId:	@(0xc3909b)},
                      @"purple": @{kId:	@(0xa66fb5)},
                      @"red": @{kId:	@(0x770001)},
                      @"brown red": @{kId:	@(0x922b05)},
                      @"grey": @{kId:	@(0x7d7f7c)},
                      @"red": @{kId:	@(0x990f4b)},
                      @"brown": @{kId:	@(0x8f7303)},
                      @"purple": @{kId:	@(0xc83cb9)},
                      @"salmon": @{kId:	@(0xfea993)},
                      @"green": @{kId:	@(0xacbb0d)},
                      @"purple": @{kId:	@(0xc071fe)},
                      @"green": @{kId:	@(0xccfd7f)},
                      @"navy": @{kId:	@(0x00022e)},
                      @"olive": @{kId:	@(0x828344)},
                      @"red": @{kId:	@(0xffc5cb)},
                      @"maroon": @{kId:	@(0xab1239)},
                      @"purple": @{kId:	@(0xb0054b)},
                      @"green": @{kId:	@(0x99cc04)},
                      @"brown": @{kId:	@(0x937c00)},
                      @"green": @{kId:	@(0x019529)},
                      @"pink": @{kId:	@(0xef1de7)},
                      @"navy": @{kId:	@(0x000435)},
                      @"green": @{kId:	@(0x42b395)},
                      @"purple": @{kId:	@(0x9d5783)},
                      @"pink grey": @{kId:	@(0xc8aca9)},
                      @"orange": @{kId:	@(0xc87606)},
                      @"red": @{kId:	@(0xaa2704)},
                      @"purple": @{kId:	@(0xe4cbff)},
                      @"orange": @{kId:	@(0xfa4224)},
                      @"blue": @{kId:	@(0x0804f9)},
                      @"green": @{kId:	@(0x5cb200)},
                      @"brown": @{kId:	@(0x76424e)},
                      @"green": @{kId:	@(0x6c7a0e)},
                      @"wheat": @{kId:	@(0xfbdd7e)},
                      @"purple": @{kId:	@(0x2a0134)},
                      @"green": @{kId:	@(0x044a05)},
                      @"pink": @{kId:	@(0xfd4659)},
                      @"blue": @{kId:	@(0x0d75f8)},
                      @"red": @{kId:	@(0xfe0002)},
                      @"yellow": @{kId:	@(0xcb9d06)},
                      @"orange": @{kId:	@(0xfb7d07)},
                      @"olive": @{kId:	@(0xb9cc81)},
                      @"lilac": @{kId:	@(0xedc8ff)},
                      @"green": @{kId:	@(0x61e160)},
                      @"blue": @{kId:	@(0x8ab8fe)},
                      @"magenta": @{kId:	@(0x920a4e)},
                      @"pink": @{kId:	@(0xfe02a2)},
                      @"orange": @{kId:	@(0x9a3001)},
                      @"green": @{kId:	@(0x65fe08)},
                      @"mint": @{kId:	@(0xbefdb7)},
                      @"brown": @{kId:	@(0xb17261)},
                      @"brown": @{kId:	@(0x885f01)},
                      @"blue": @{kId:	@(0x02ccfe)},
                      @"green": @{kId:	@(0xc1fd95)},
                      @"brown": @{kId:	@(0x836539)},
                      @"red": @{kId:	@(0xfb2943)},
                      @"green": @{kId:	@(0x84b701)},
                      @"leather": @{kId:	@(0xb66325)},
                      @"brown": @{kId:	@(0x7f5112)},
                      @"green": @{kId:	@(0x5fa052)},
                      @"blue": @{kId:	@(0x6dedfd)},
                      @"aqua": @{kId:	@(0x0bf9ea)},
                      @"lavender": @{kId:	@(0xc760ff)},
                      @"off white": @{kId:	@(0xffffcb)},
                      @"purple": @{kId:	@(0xf6cefc)},
                      @"navy": @{kId:	@(0x155084)},
                      @"pink": @{kId:	@(0xf5054f)},
                      @"olive": @{kId:	@(0x645403)},
                      @"brown": @{kId:	@(0x7a5901)},
                      @"green": @{kId:	@(0xa8b504)},
                      @"green": @{kId:	@(0x3d9973)},
                      @"blue": @{kId:	@(0x000133)},
                      @"green": @{kId:	@(0x76a973)},
                      @"navy": @{kId:	@(0x2e5a88)},
                      @"mint": @{kId:	@(0x0bf77d)},
                      @"orange": @{kId:	@(0xbd6c48)},
                      @"purple": @{kId:	@(0xac1db8)},
                      @"jade": @{kId:	@(0x2baf6a)},
                      @"blue": @{kId:	@(0x26f7fd)},
                      @"green": @{kId:	@(0xaefd6c)},
                      @"khaki": @{kId:	@(0x9b8f55)},
                      @"yellow": @{kId:	@(0xffad01)},
                      @"gold": @{kId:	@(0xc69c04)},
                      @"yellow": @{kId:	@(0xf4d054)},
                      @"pink": @{kId:	@(0xde9dac)},
                      @"green": @{kId:	@(0x05480d)},
                      @"yellow": @{kId:	@(0xc9ae74)},
                      @"brown": @{kId:	@(0x60460f)},
                      @"green": @{kId:	@(0x98f6b0)},
                      @"blue": @{kId:	@(0x8af1fe)},
                      @"aquamarine": @{kId:	@(0x2ee8bb)},
                      @"green": @{kId:	@(0x11875d)},
                      @"pink": @{kId:	@(0xfdb0c0)},
                      @"orange": @{kId:	@(0xb16002)},
                      @"red": @{kId:	@(0xf7022a)},
                      @"yellow": @{kId:	@(0xd5ab09)},
                      @"grey": @{kId:	@(0x86775f)},
                      @"khaki": @{kId:	@(0xc69f59)},
                      @"grey": @{kId:	@(0x7a687f)},
                      @"aquamarine": @{kId:	@(0x042e60)},
                      @"pink": @{kId:	@(0xc88d94)},
                      @"turquoise": @{kId:	@(0xa5fbd5)},
                      @"yellow": @{kId:	@(0xfffe71)},
                      @"purple": @{kId:	@(0x6241c7)},
                      @"yellow": @{kId:	@(0xfffe40)},
                      @"red": @{kId:	@(0xd3494e)},
                      @"brown grey": @{kId:	@(0x985e2b)},
                      @"brown": @{kId:	@(0xa6814c)},
                      @"magenta": @{kId:	@(0xff08e8)},
                      @"brown": @{kId:	@(0x9d7651)},
                      @"off white": @{kId:	@(0xfeffca)},
                      @"purple": @{kId:	@(0x98568d)},
                      @"red": @{kId:	@(0x9e003a)},
                      @"green": @{kId:	@(0x287c37)},
                      @"brown": @{kId:	@(0xb96902)},
                      @"red": @{kId:	@(0xba6873)},
                      @"red": @{kId:	@(0xff7855)},
                      @"green": @{kId:	@(0x94b21c)},
                      @"silver": @{kId:	@(0xc5c9c7)},
                      @"purple": @{kId:	@(0x661aee)},
                      @"purple": @{kId:	@(0x6140ef)},
                      @"green": @{kId:	@(0x9be5aa)},
                      @"brown": @{kId:	@(0x7b5804)},
                      @"blue": @{kId:	@(0x276ab3)},
                      @"amber": @{kId:	@(0xfeb308)},
                      @"green": @{kId:	@(0x8cfd7e)},
                      @"blue": @{kId:	@(0x6488ea)},
                      @"blue": @{kId:	@(0x056eee)},
                      @"gold": @{kId:	@(0xb27a01)},
                      @"turquoise": @{kId:	@(0x0ffef9)},
                      @"red": @{kId:	@(0xfa2a55)},
                      @"red": @{kId:	@(0x820747)},
                      @"grey": @{kId:	@(0x7a6a4f)},
                      @"orange": @{kId:	@(0xf4320c)},
                      @"orange": @{kId:	@(0xa13905)},
                      @"grey": @{kId:	@(0x6f828a)},
                      @"purple": @{kId:	@(0xa55af4)},
                      @"violet": @{kId:	@(0xad0afd)},
                      @"blue": @{kId:	@(0x004577)},
                      @"green": @{kId:	@(0x658d6d)},
                      @"pink": @{kId:	@(0xca7b80)},
                      @"turquoise": @{kId:	@(0x005249)},
                      @"green": @{kId:	@(0x2b5d34)},
                      @"yellow": @{kId:	@(0xbff128)},
                      @"gold": @{kId:	@(0xb59410)},
                      @"blue": @{kId:	@(0x2976bb)},
                      @"navy": @{kId:	@(0x014182)},
                      @"red": @{kId:	@(0xbb3f3f)},
                      @"pink": @{kId:	@(0xfc2647)},
                      @"bronze": @{kId:	@(0xa87900)},
                      @"teal": @{kId:	@(0x82cbb2)},
                      @"olive": @{kId:	@(0x667c3e)},
                      @"pink": @{kId:	@(0xfe46a5)},
                      @"pink": @{kId:	@(0xfe83cc)},
                      @"green": @{kId:	@(0x94a617)},
                      @"yellow": @{kId:	@(0xa88905)},
                      @"brown": @{kId:	@(0x7f5f00)},
                      @"purple": @{kId:	@(0x9e43a2)},
                      @"green": @{kId:	@(0x062e03)},
                      @"brown": @{kId:	@(0x8a6e45)},
                      @"pink": @{kId:	@(0xcc7a8b)},
                      @"red": @{kId:	@(0x9e0168)},
                      @"yellow": @{kId:	@(0xfdff38)},
                      @"green": @{kId:	@(0xc0fa8b)},
                      @"yellow": @{kId:	@(0xeedc5b)},
                      @"green": @{kId:	@(0x7ebd01)},
                      @"denim": @{kId:	@(0x3b5b92)},
                      @"teal": @{kId:	@(0x01889f)},
                      @"blue": @{kId:	@(0x3d7afd)},
                      @"purple": @{kId:	@(0x5f34e7)},
                      @"indigo": @{kId:	@(0x6d5acf)},
                      @"green": @{kId:	@(0x748500)},
                      @"camouflage": @{kId:	@(0x706c11)},
                      @"maroon": @{kId:	@(0x3c0008)},
                      @"purple": @{kId:	@(0xcb00f5)},
                      @"green": @{kId:	@(0x002d04)},
                      @"blue": @{kId:	@(0x658cbb)},
                      @"olive": @{kId:	@(0x749551)},
                      @"green": @{kId:	@(0xb9ff66)},
                      @"green": @{kId:	@(0x9dc100)},
                      @"yellow": @{kId:	@(0xfaee66)},
                      @"blue": @{kId:	@(0x7efbb3)},
                      @"magenta": @{kId:	@(0x7b002c)},
                      @"mauve": @{kId:	@(0xc292a1)},
                      @"navy": @{kId:	@(0x017b92)},
                      @"yellow": @{kId:	@(0xfcc006)},
                      @"green": @{kId:	@(0x657432)},
                      @"orange": @{kId:	@(0xd8863b)},
                      @"grey": @{kId:	@(0x738595)},
                      @"neon purple": @{kId:	@(0xaa23ff)},
                      @"neon green": @{kId:	@(0x08ff08)},
                      @"yellow": @{kId:	@(0x9b7a01)},
                      @"magenta": @{kId:	@(0xf29e8e)},
                      @"green": @{kId:	@(0x6fc276)},
                      @"orange": @{kId:	@(0xff5b00)},
                      @"yellow": @{kId:	@(0xfdff52)},
                      @"grey": @{kId:	@(0x866f85)},
                      @"green": @{kId:	@(0x8ffe09)},
                      @"lavender": @{kId:	@(0xeecffe)},
                      @"indigo": @{kId:	@(0x510ac9)},
                      @"green": @{kId:	@(0x4f9153)},
                      @"red": @{kId:	@(0x9f2305)},
                      @"khaki": @{kId:	@(0x728639)},
                      @"pink": @{kId:	@(0xde0c62)},
                      @"purple": @{kId:	@(0x916e99)},
                      @"orange": @{kId:	@(0xffb16d)},
                      @"olive": @{kId:	@(0x3c4d03)},
                      @"grey": @{kId:	@(0x7f7053)},
                      @"grey": @{kId:	@(0x77926f)},
                      @"blue": @{kId:	@(0x010fcc)},
                      @"violet": @{kId:	@(0xceaefa)},
                      @"blue": @{kId:	@(0x8f99fb)},
                      @"blue": @{kId:	@(0xc6fcff)},
                      @"indigo": @{kId:	@(0x5539cc)},
                      @"camouflage": @{kId:	@(0x544e03)},
                      @"turquoise": @{kId:	@(0x017a79)},
                      @"teal": @{kId:	@(0x01f9c6)},
                      @"brown": @{kId:	@(0xc9b003)},
                      @"green": @{kId:	@(0x929901)},
                      @"green": @{kId:	@(0x0b5509)},
                      @"purple": @{kId:	@(0xa00498)},
                      @"aquamarine": @{kId:	@(0x2000b1)},
                      @"purple": @{kId:	@(0x94568c)},
                      @"yellow": @{kId:	@(0xc2be0e)},
                      @"grey": @{kId:	@(0x748b97)},
                      @"blue": @{kId:	@(0x665fd1)},
                      @"purple": @{kId:	@(0x9c6da5)},
                      @"red": @{kId:	@(0xc44240)},
                      @"maroon": @{kId:	@(0xa24857)},
                      @"purple": @{kId:	@(0x825f87)},
                      @"red": @{kId:	@(0xc9643b)},
                      @"green": @{kId:	@(0x90b134)},
                      @"blue": @{kId:	@(0x01386a)},
                      @"teal": @{kId:	@(0x25a36f)},
                      @"grey": @{kId:	@(0x59656d)},
                      @"green": @{kId:	@(0x75fd63)},
                      @"green": @{kId:	@(0x21fc0d)},
                      @"blue": @{kId:	@(0x5a86ad)},
                      @"gold": @{kId:	@(0xfec615)},
                      @"yellow": @{kId:	@(0xfffd01)},
                      @"lavender": @{kId:	@(0xdfc5fe)},
                      @"brown": @{kId:	@(0xb26400)},
                      @"brown": @{kId:	@(0x7f5e00)},
                      @"orange": @{kId:	@(0xde7e5d)},
                      @"green": @{kId:	@(0x048243)},
                      @"eggshell": @{kId:	@(0xffffd4)},
                      @"denim": @{kId:	@(0x3b638c)},
                      @"yellow": @{kId:	@(0xb79400)},
                      @"purple": @{kId:	@(0x84597e)},
                      @"brown": @{kId:	@(0x411900)},
                      @"red": @{kId:	@(0x7b0323)},
                      @"blue": @{kId:	@(0x04d9ff)},
                      @"green": @{kId:	@(0x667e2c)},
                      @"tan": @{kId:	@(0xfbeeac)},
                      @"blue": @{kId:	@(0xd7fffe)},
                      @"blue": @{kId:	@(0x4e7496)},
                      @"mauve": @{kId:	@(0x874c62)},
                      @"blue": @{kId:	@(0xd5ffff)},
                      @"grey purple": @{kId:	@(0x826d8c)},
                      @"pink": @{kId:	@(0xffbacd)},
                      @"green": @{kId:	@(0xd1ffbd)},
                      @"navy": @{kId:	@(0x448ee4)},
                      @"green": @{kId:	@(0x05472a)},
                      @"pink": @{kId:	@(0xd5869d)},
                      @"purple": @{kId:	@(0x3d0734)},
                      @"red": @{kId:	@(0x4a0100)},
                      @"red": @{kId:	@(0xf8481c)},
                      @"green": @{kId:	@(0x02590f)},
                      @"green": @{kId:	@(0x89a203)},
                      @"pink": @{kId:	@(0xe03fd8)},
                      @"pink": @{kId:	@(0xd58a94)},
                      @"green": @{kId:	@(0x7bb274)},
                      @"camo": @{kId:	@(0x526525)},
                      @"pink": @{kId:	@(0xc94cbe)},
                      @"pink": @{kId:	@(0xdb4bda)},
                      @"red": @{kId:	@(0x9e3623)},
                      @"red": @{kId:	@(0xb5485d)},
                      @"brown": @{kId:	@(0x735c12)},
                      @"brown": @{kId:	@(0x9c6d57)},
                      @"green": @{kId:	@(0x028f1e)},
                      @"brown": @{kId:	@(0xb1916e)},
                      @"blue": @{kId:	@(0x49759c)},
                      @"umber": @{kId:	@(0xa0450e)},
                      @"green": @{kId:	@(0x39ad48)},
                      @"orange": @{kId:	@(0xb66a50)},
                      @"aqua": @{kId:	@(0x8cffdb)},
                      @"olive": @{kId:	@(0xa4be5c)},
                      @"orange": @{kId:	@(0xcb7723)},
                      @"aqua": @{kId:	@(0x05696b)},
                      @"purple": @{kId:	@(0xce5dae)},
                      @"salmon": @{kId:	@(0xc85a53)},
                      @"grey": @{kId:	@(0x96ae8d)},
                      @"green": @{kId:	@(0x1fa774)},
                      @"green": @{kId:	@(0x7a9703)},
                      @"beige": @{kId:	@(0xac9362)},
                      @"green": @{kId:	@(0x01a049)},
                      @"red": @{kId:	@(0xd9544d)},
                      @"magenta": @{kId:	@(0xfa5ff7)},
                      @"blue": @{kId:	@(0x82cafc)},
                      @"cyan": @{kId:	@(0xacfffc)},
                      @"orange": @{kId:	@(0xfcb001)},
                      @"red": @{kId:	@(0x910951)},
                      @"red": @{kId:	@(0xfe2c54)},
                      @"pink": @{kId:	@(0xc875c4)},
                      @"yellow": @{kId:	@(0xcdc50a)},
                      @"orange": @{kId:	@(0xfd411e)},
                      @"red": @{kId:	@(0x9a0200)},
                      @"orange": @{kId:	@(0xbe6400)},
                      @"blue": @{kId:	@(0x030aa7)},
                      @"pink": @{kId:	@(0xfe019a)},
                      @"pink": @{kId:	@(0xf7879a)},
                      @"grey": @{kId:	@(0x887191)},
                      @"red": @{kId:	@(0xb00149)},
                      @"aqua": @{kId:	@(0x12e193)},
                      @"salmon": @{kId:	@(0xfe7b7c)},
                      @"orange": @{kId:	@(0xff9408)},
                      @"brown": @{kId:	@(0x6a6e09)},
                      @"red": @{kId:	@(0x8b2e16)},
                      @"green": @{kId:	@(0x696112)},
                      @"orange": @{kId:	@(0xe17701)},
                      @"green": @{kId:	@(0x0a481e)},
                      @"grey": @{kId:	@(0x343837)},
                      @"pink": @{kId:	@(0xffb7ce)},
                      @"blue": @{kId:	@(0x6a79f7)},
                      @"indigo": @{kId:	@(0x5d06e9)},
                      @"brown": @{kId:	@(0x3d1c02)},
                      @"grey": @{kId:	@(0x82a67d)},
                      @"red": @{kId:	@(0xbe0119)},
                      @"green": @{kId:	@(0xc9ff27)},
                      @"olive": @{kId:	@(0x373e02)},
                      @"orange": @{kId:	@(0xa9561e)},
                      @"purple": @{kId:	@(0xcaa0ff)},
                      @"orange": @{kId:	@(0xca6641)},
                      @"aqua": @{kId:	@(0x02d8e9)},
                      @"sage": @{kId:	@(0x88b378)},
                      @"red": @{kId:	@(0x980002)},
                      @"pink": @{kId:	@(0xcb0162)},
                      @"green": @{kId:	@(0x5cac2d)},
                      @"olive": @{kId:	@(0x769958)},
                      @"blue": @{kId:	@(0xa2bffe)},
                      @"blue": @{kId:	@(0x10a674)},
                      @"green": @{kId:	@(0x06b48b)},
                      @"tan": @{kId:	@(0xaf884a)},
                      @"green": @{kId:	@(0x0b8b87)},
                      @"orange": @{kId:	@(0xffa756)},
                      @"green": @{kId:	@(0xa2a415)},
                      @"green": @{kId:	@(0x154406)},
                      @"lavender": @{kId:	@(0x856798)},
                      @"violet": @{kId:	@(0x34013f)},
                      @"purple": @{kId:	@(0x632de9)},
                      @"cyan": @{kId:	@(0x0a888a)},
                      @"olive": @{kId:	@(0x6f7632)},
                      @"pink": @{kId:	@(0xd46a7e)},
                      @"blue": @{kId:	@(0x1e488f)},
                      @"purple": @{kId:	@(0xbc13fe)},
                      @"turquoise": @{kId:	@(0x7ef4cc)},
                      @"green": @{kId:	@(0x76cd26)},
                      @"green": @{kId:	@(0x74a662)},
                      @"red": @{kId:	@(0x80013f)},
                      @"blue": @{kId:	@(0xb1d1fc)},
                      @"off white": @{kId:	@(0xffffe4)},
                      @"blue": @{kId:	@(0x0652ff)},
                      @"turquoise": @{kId:	@(0x045c5a)},
                      @"purple": @{kId:	@(0x5729ce)},
                      @"blue": @{kId:	@(0x069af3)},
                      @"red": @{kId:	@(0xff000d)},
                      @"pink": @{kId:	@(0xf10c45)},
                      @"blue": @{kId:	@(0x5170d7)},
                      @"olive": @{kId:	@(0xacbf69)},
                      @"purple": @{kId:	@(0x6c3461)},
                      @"grey": @{kId:	@(0x5e819d)},
                      @"purple": @{kId:	@(0x601ef9)},
                      @"yellow": @{kId:	@(0xb0dd16)},
                      @"green": @{kId:	@(0xcdfd02)},
                      @"blue": @{kId:	@(0x2c6fbb)},
                      @"red": @{kId:	@(0xc0737a)},
                      @"violet": @{kId:	@(0xd6b4fc)},
                      @"navy": @{kId:	@(0x020035)},
                      @"purple": @{kId:	@(0x703be7)},
                      @"red": @{kId:	@(0xfd3c06)},
                      @"magenta": @{kId:	@(0x960056)},
                      @"green": @{kId:	@(0x40a368)},
                      @"aqua": @{kId:	@(0x03719c)},
                      @"coral": @{kId:	@(0xfc5a50)},
                      @"cream": @{kId:	@(0xffffc2)},
                      @"red": @{kId:	@(0x7f2b0a)},
                      @"orange": @{kId:	@(0xb04e0f)},
                      @"red": @{kId:	@(0xa03623)},
                      @"sage": @{kId:	@(0x87ae73)},
                      @"grey": @{kId:	@(0x789b73)},
                      @"white": @{kId:	@(0xffffff)},
                      @"blue": @{kId:	@(0x98eff9)},
                      @"green": @{kId:	@(0x658b38)},
                      @"blue": @{kId:	@(0x5a7d9a)},
                      @"purple": @{kId:	@(0x380835)},
                      @"yellow": @{kId:	@(0xfffe7a)},
                      @"green": @{kId:	@(0x5ca904)},
                      @"grey": @{kId:	@(0xd8dcd6)},
                      @"green": @{kId:	@(0xa5a502)},
                      @"pink": @{kId:	@(0xd648d7)},
                      @"aqua": @{kId:	@(0x047495)},
                      @"purple": @{kId:	@(0xb790d4)},
                      @"blue": @{kId:	@(0x5b7c99)},
                      @"grey": @{kId:	@(0x607c8e)},
                      @"olive": @{kId:	@(0x0b4008)},
                      @"fuchsia": @{kId:	@(0xed0dd9)},
                      @"red": @{kId:	@(0x8c000f)},
                      @"yellow": @{kId:	@(0xffff84)},
                      @"gold": @{kId:	@(0xbf9005)},
                      @"yellow": @{kId:	@(0xd2bd0a)},
                      @"red": @{kId:	@(0xff474c)},
                      @"blue": @{kId:	@(0x0485d1)},
                      @"pink": @{kId:	@(0xffcfdc)},
                      @"blue": @{kId:	@(0x040273)},
                      @"orange": @{kId:	@(0xa83c09)},
                      @"teal": @{kId:	@(0x90e4c1)},
                      @"grey": @{kId:	@(0x516572)},
                      @"gold": @{kId:	@(0xfac205)},
                      @"yellow": @{kId:	@(0xd5b60a)},
                      @"grey": @{kId:	@(0x363737)},
                      @"olive": @{kId:	@(0x4b5d16)},
                      @"grey": @{kId:	@(0x6b8ba4)},
                      @"green": @{kId:	@(0x80f9ad)},
                      @"brown grey": @{kId:	@(0xa57e52)},
                      @"green": @{kId:	@(0xa9f971)},
                      @"orange": @{kId:	@(0xc65102)},
                      @"yellow": @{kId:	@(0xe2ca76)},
                      @"green": @{kId:	@(0xb0ff9d)},
                      @"mint": @{kId:	@(0x9ffeb0)},
                      @"orange": @{kId:	@(0xfdaa48)},
                      @"pink": @{kId:	@(0xfe01b1)},
                      @"chartreuse": @{kId:	@(0xc1f80a)},
                      @"deep purple": @{kId:	@(0x36013f)},
                      @"brown": @{kId:	@(0x341c02)},
                      @"grey": @{kId:	@(0xb9a281)},
                      @"green": @{kId:	@(0x8eab12)},
                      @"green": @{kId:	@(0x9aae07)},
                      @"green": @{kId:	@(0x02ab2e)},
                      @"green": @{kId:	@(0x7af9ab)},
                      @"blue": @{kId:	@(0x137e6d)},
                      @"khaki": @{kId:	@(0xaaa662)},
                      @"burgundy": @{kId:	@(0x610023)},
                      @"teal": @{kId:	@(0x014d4e)},
                      @"red": @{kId:	@(0x8f1402)},
                      @"purple": @{kId:	@(0x4b006e)},
                      @"purple": @{kId:	@(0x580f41)},
                      @"mint": @{kId:	@(0x8fff9f)},
                      @"gold": @{kId:	@(0xdbb40c)},
                      @"blue": @{kId:	@(0xa2cffe)},
                      @"green": @{kId:	@(0xc0fb2d)},
                      @"purple": @{kId:	@(0xbe03fd)},
                      @"red": @{kId:	@(0x840000)},
                      @"blue": @{kId:	@(0xd0fefe)},
                      @"green": @{kId:	@(0x3f9b0b)},
                      @"navy": @{kId:	@(0x01153e)},
                      @"aquamarine": @{kId:	@(0x04d8b2)},
                      @"sienna": @{kId:	@(0xc04e01)},
                      @"green": @{kId:	@(0x0cff0c)},
                      @"blue": @{kId:	@(0x0165fc)},
                      @"red": @{kId:	@(0xcf6275)},
                      @"pink": @{kId:	@(0xffd1df)},
                      @"yellow": @{kId:	@(0xceb301)},
                      @"indigo": @{kId:	@(0x380282)},
                      @"green": @{kId:	@(0xaaff32)},
                      @"green": @{kId:	@(0x53fca1)},
                      @"periwinkle": @{kId:	@(0x8e82fe)},
                      @"pink": @{kId:	@(0xcb416b)},
                      @"olive": @{kId:	@(0x677a04)},
                      @"orange": @{kId:	@(0xffb07c)},
                      @"green": @{kId:	@(0xc7fdb5)},
                      @"brown": @{kId:	@(0xad8150)},
                      @"hot pink": @{kId:	@(0xff028d)},
                      @"black": @{kId:	@(0x000000)},
                      @"lilac": @{kId:	@(0xcea2fd)},
                      @"navy": @{kId:	@(0x001146)},
                      @"blue": @{kId:	@(0x0504aa)},
                      @"beige": @{kId:	@(0xe6daa6)},
                      @"salmon": @{kId:	@(0xff796c)},
                      @"olive": @{kId:	@(0x6e750e)},
                      @"maroon": @{kId:	@(0x650021)},
                      @"green": @{kId:	@(0x01ff07)},
                      @"purple": @{kId:	@(0x35063e)},
                      @"mauve": @{kId:	@(0xae7181)},
                      @"green": @{kId:	@(0x06470c)},
                      @"aqua": @{kId:	@(0x13eac9)},
                      @"cyan": @{kId:	@(0x00ffff)},
                      @"tan": @{kId:	@(0xd1b26f)},
                      @"blue": @{kId:	@(0x00035b)},
                      @"lavender": @{kId:	@(0xc79fef)},
                      @"turquoise": @{kId:	@(0x06c2ac)},
                      @"green": @{kId:	@(0x033500)},
                      @"violet": @{kId:	@(0x9a0eea)},
                      @"purple": @{kId:	@(0xbf77f6)},
                      @"green": @{kId:	@(0x89fe05)},
                      @"grey": @{kId:	@(0x929591)},
                      @"blue": @{kId:	@(0x75bbfd)},
                      @"yellow": @{kId:	@(0xffff14)},
                      @"magenta": @{kId:	@(0xc20078)},
                      @"green": @{kId:	@(0x96f97b)},
                      @"orange": @{kId:	@(0xf97306)},
                      @"teal": @{kId:	@(0x029386)},
                      @"blue": @{kId:	@(0x95d0fc)},
                      @"red": @{kId:	@(0xe50000)},
                      @"brown": @{kId:	@(0x653700)},
                      @"pink": @{kId:	@(0xff81c0)},
                      @"blue": @{kId:	@(0x0343df)},
                      @"green": @{kId:	@(0x15b01a)},
                      @"purple": @{kId:	@(0x7e1e9c)},
                      };
}


- (NSString *)nameForColor:(UIColor *)color {
    
    CGFloat iR = 0.0f;
    CGFloat iG = 0.0f;
    CGFloat iB = 0.0f;
    CGFloat iA = 0.0f;
    
    [color getRed:&iR green:&iG blue:&iB alpha:&iA];
    
    CGFloat minDistance = CGFLOAT_MAX;
    NSString *colorKey = nil;
    
    for (NSString *key in self.colorMap) {
        @autoreleasepool {
            UIColor *currentColor = [self colorFromRGBFloat:[self.colorMap[key][kId] intValue]];
            
            CGFloat cR, cG, cB, cA = 0.0f;
            [currentColor getRed:&cR green:&cG blue:&cB alpha:&cA];
            
            // Calculate euclidean distance
            
            // Deltas
            CGFloat dR = iR - cR;
            CGFloat dG = iG - cG;
            CGFloat dB = iB - cB;
            
            CGFloat a = pow(dR, 2.0f);
            CGFloat b = pow(dG, 2.0f);
            CGFloat c = pow(dB, 2.0f);
            
            CGFloat d = sqrt(a + b + c);
            
            if (d < minDistance) {
                minDistance = d;
                colorKey = key;
            }
        }
    }
    return colorKey;
}


@end

